const ADD_TODO = "ADD_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const EDIT_TODO = "EDIT_TODO";
const GET_TODO = "GET_TODO";

//fetching
const SET_TODOS = "SET_TODOS";
const START_SETTING_TODOS = "START_SETTING_TODOS ";
const SET_TODOS_FAIL = "SET_TODOS_FAIL ";
export {
  ADD_TODO,
  REMOVE_TODO,
  TOGGLE_TODO,
  EDIT_TODO,
  GET_TODO,
  SET_TODOS,
  START_SETTING_TODOS,
  SET_TODOS_FAIL,
};
